[package]
name = "hyper-mcp"
version = "0.1.0"
edition = "2024"
authors = ["Tuan Anh Tran <me@tuananh.org>"]
description = " A fast, secure MCP server that extends its capabilities through WebAssembly plugins"
keywords = ["rust", "ai", "mcp", "cli"]
categories = ["command-line-utilities"]
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/tuananh/hyper-mcp"
homepage = "https://github.com/tuananh/hyper-mcp"
documentation = "https://github.com/tuananh/hyper-mcp"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }
anyhow = "1.0"
extism = "1.10.0"
sha2 = "0.10.8"
hex = "0.4.3"
oci-client = "0.14.0"
tar = "0.4.44"
flate2 = "1.1.1"
clap = { version = "4.5.36", features = ["derive", "env"] }
dirs = "6.0"
docker_credential = "1.3.1"
log = "0.4.27"
sigstore = { version = "0.11.0", features = ["cosign", "verify", "bundle", "full-native-tls"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", rev = "9d6f9a2e0d199c6c7f2731bd6f8f7143af060a6b", features = ["server", "transport-io", "transport-sse", "transport-sse-server"] }

[[bin]]
name = "hyper-mcp"
path = "src/main.rs"
